"""Fix user_oshi relationship

Revision ID: 0e57b1ffebf8
Revises: 2c0216dbbd19
Create Date: 2025-03-25 20:10:58.170458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e57b1ffebf8'
down_revision = '2c0216dbbd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('tweet_username', sa.String(length=120), nullable=False),
    sa.Column('tweet_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('tweet_included_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('tweet_text', sa.String(length=255), nullable=False),
    sa.Column('tweet_translated_text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tweet_id'),
    sa.UniqueConstraint('tweet_username')
    )
    op.create_table('tweet_user',
    sa.Column('tweet_internal_id', sa.String(length=120), nullable=False),
    sa.Column('tweet_id', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('tweet_internal_id'),
    sa.UniqueConstraint('tweet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_user')
    op.drop_table('tweet')
    # ### end Alembic commands ###
