"""change post table to store emoji

Revision ID: 1dcabeabf6a2
Revises: b3da719b32e7
Create Date: 2025-04-08 20:16:45.466701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dcabeabf6a2'
down_revision = 'b3da719b32e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('tweet_id',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=64),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('tweet_userid',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('tweet_username',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('tweet_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('tweet_included_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('tweet_text',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=512),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('tweet_translated_text',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=512),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('tweet_about',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index('tweet_userid')
        batch_op.drop_index('tweet_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('tweet_username', ['tweet_username'], unique=True)
        batch_op.create_index('tweet_userid', ['tweet_userid'], unique=True)
        batch_op.alter_column('tweet_about',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=120),
               existing_nullable=False)
        batch_op.alter_column('tweet_translated_text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=512),
               existing_nullable=False)
        batch_op.alter_column('tweet_text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=512),
               existing_nullable=False)
        batch_op.alter_column('tweet_included_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('tweet_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('tweet_username',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=120),
               existing_nullable=False)
        batch_op.alter_column('tweet_userid',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=64),
               existing_nullable=False)
        batch_op.alter_column('tweet_id',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=64),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
