"""fixed

Revision ID: 28c0ebef7846
Revises: 0e57b1ffebf8
Create Date: 2025-03-25 22:53:55.579082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28c0ebef7846'
down_revision = '0e57b1ffebf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet_user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=True))

    # ### end Alembic commands ###
