"""Fix user_oshi relationship

Revision ID: 2c0216dbbd19
Revises: f388fc4a7e4a
Create Date: 2025-03-25 19:59:40.179266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c0216dbbd19'
down_revision = 'f388fc4a7e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet_user', schema=None) as batch_op:
        batch_op.drop_index('tweet_id')

    op.drop_table('tweet_user')
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_index('tweet_username')

    op.drop_table('tweet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('tweet_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tweet_username', mysql.VARCHAR(collation='utf8mb3_bin', length=120), nullable=False),
    sa.Column('tweet_date', mysql.TIMESTAMP(), nullable=False),
    sa.Column('tweet_included_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('tweet_text', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=False),
    sa.Column('tweet_translated_text', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=False),
    sa.PrimaryKeyConstraint('tweet_id'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.create_index('tweet_username', ['tweet_username'], unique=True)

    op.create_table('tweet_user',
    sa.Column('tweet_internal_id', mysql.VARCHAR(collation='utf8mb3_bin', length=120), nullable=False),
    sa.Column('tweet_id', mysql.VARCHAR(collation='utf8mb3_bin', length=120), nullable=False),
    sa.Column('bio', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tweet_user_ibfk_1'),
    sa.PrimaryKeyConstraint('tweet_internal_id'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tweet_user', schema=None) as batch_op:
        batch_op.create_index('tweet_id', ['tweet_id'], unique=True)

    # ### end Alembic commands ###
