"""Change login_id to email

Revision ID: 4f34e0ef462b
Revises: 464e7ef9abf8
Create Date: 2025-03-20 23:25:49.796427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f34e0ef462b'
down_revision = '464e7ef9abf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.drop_index('login_id')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('login_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_id', mysql.VARCHAR(collation='utf8mb3_bin', length=120), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('login_id', ['login_id'], unique=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
