"""Add reply_log table

Revision ID: 583c07151671
Revises: 1dcabeabf6a2
Create Date: 2025-04-12 01:59:24.147841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '583c07151671'
down_revision = '1dcabeabf6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.String(length=64), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweet_likes',
    sa.Column('tweet_id', sa.BigInteger(), nullable=False),
    sa.Column('tweet_userid', sa.String(length=255), nullable=False),
    sa.Column('liked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tweet_id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('tweet_text',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('tweet_translated_text',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('tweet_translated_text',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('tweet_text',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    op.drop_table('tweet_likes')
    op.drop_table('reply_log')
    # ### end Alembic commands ###
