"""3NF schema refactoring applied

Revision ID: 9dcb06558d73
Revises: a1b0db22f2ed
Create Date: 2025-05-02 20:29:26.568413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dcb06558d73'
down_revision = 'a1b0db22f2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_internal_id', sa.String(length=120), nullable=False))
        batch_op.create_foreign_key(None, 'twitter_user', ['author_internal_id'], ['twitter_internal_id'])
        batch_op.drop_column('tweet_userid')
        batch_op.drop_column('tweet_username')

    with op.batch_alter_table('reply_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_tweet_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'post', ['post_tweet_id'], ['tweet_id'])
        batch_op.drop_column('tweet_id')

    with op.batch_alter_table('tweet_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_tweet_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('liked_by_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['liked_by_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['post_tweet_id'], ['tweet_id'])
        batch_op.drop_column('tweet_id')
        batch_op.drop_column('tweet_userid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter_user_internal_id', sa.String(length=120), nullable=True))
        batch_op.drop_index('tweet_id')
        batch_op.create_unique_constraint(None, ['twitter_user_internal_id'])
        batch_op.create_foreign_key(None, 'twitter_user', ['twitter_user_internal_id'], ['twitter_internal_id'])
        batch_op.drop_column('tweet_id')

    with op.batch_alter_table('user_oshi', schema=None) as batch_op:
        batch_op.alter_column('oshi_internal_id',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.create_unique_constraint(None, ['oshi_internal_id'])
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_oshi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('oshi_internal_id',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tweet_id', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('tweet_id', ['tweet_id'], unique=True)
        batch_op.drop_column('twitter_user_internal_id')

    with op.batch_alter_table('tweet_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tweet_userid', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('tweet_id', mysql.BIGINT(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('liked_by_user_id')
        batch_op.drop_column('post_tweet_id')

    with op.batch_alter_table('reply_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tweet_id', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_tweet_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tweet_username', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('tweet_userid', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_internal_id')

    # ### end Alembic commands ###
