"""add twitter_user table

Revision ID: a1b0db22f2ed
Revises: 583c07151671
Create Date: 2025-05-02 19:29:14.263428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1b0db22f2ed'
down_revision = '583c07151671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user',
    sa.Column('twitter_internal_id', sa.String(length=120), nullable=False),
    sa.Column('twitter_id', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('twitter_internal_id'),
    sa.UniqueConstraint('twitter_id')
    )
    with op.batch_alter_table('tweet_user', schema=None) as batch_op:
        batch_op.drop_index('tweet_id')

    op.drop_table('tweet_user')
    with op.batch_alter_table('user_oshi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('oshi_internal_id', sa.String(length=120), nullable=True))
        batch_op.drop_index('oshi_tweet_id')
        batch_op.drop_constraint('user_oshi_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'twitter_user', ['oshi_internal_id'], ['twitter_internal_id'])
        batch_op.drop_column('oshi_tweet_id')
        batch_op.drop_column('oshi_username')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_oshi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('oshi_username', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('oshi_tweet_id', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_oshi_ibfk_1', 'user', ['id'], ['id'])
        batch_op.create_index('oshi_tweet_id', ['oshi_tweet_id'], unique=True)
        batch_op.drop_column('oshi_internal_id')
        batch_op.drop_column('user_id')

    op.create_table('tweet_user',
    sa.Column('tweet_internal_id', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('tweet_id', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tweet_user_ibfk_1'),
    sa.PrimaryKeyConstraint('tweet_internal_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tweet_user', schema=None) as batch_op:
        batch_op.create_index('tweet_id', ['tweet_id'], unique=True)

    op.drop_table('twitter_user')
    # ### end Alembic commands ###
