"""change tweet_id and tweet_userid to String

Revision ID: b3da719b32e7
Revises: d46e16c7dbda
Create Date: 2025-04-08 19:46:51.899969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3da719b32e7'
down_revision = 'd46e16c7dbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('tweet_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('tweet_userid',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=120),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('tweet_userid',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=120),
               existing_nullable=False)
        batch_op.alter_column('tweet_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
