"""create post table

Revision ID: d46e16c7dbda
Revises: 28c0ebef7846
Create Date: 2025-04-08 19:41:07.298886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd46e16c7dbda'
down_revision = '28c0ebef7846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('tweet_userid', sa.String(length=120), nullable=False),
    sa.Column('tweet_username', sa.String(length=120), nullable=False),
    sa.Column('tweet_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('tweet_included_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('tweet_text', sa.String(length=512), nullable=False),
    sa.Column('tweet_translated_text', sa.String(length=512), nullable=False),
    sa.Column('tweet_about', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('tweet_id'),
    sa.UniqueConstraint('tweet_userid'),
    sa.UniqueConstraint('tweet_username')
    )
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_index('tweet_username')

    op.drop_table('tweet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('tweet_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tweet_username', mysql.VARCHAR(collation='utf8mb3_bin', length=120), nullable=False),
    sa.Column('tweet_date', mysql.TIMESTAMP(), nullable=False),
    sa.Column('tweet_included_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('tweet_text', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=False),
    sa.Column('tweet_translated_text', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=False),
    sa.PrimaryKeyConstraint('tweet_id'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.create_index('tweet_username', ['tweet_username'], unique=True)

    op.drop_table('post')
    # ### end Alembic commands ###
